services:
  gold-bot:
    build: .
    ports:
      - "9051:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - TZ=Asia/Taipei
    command: flask run --host=0.0.0.0 --port=5001
    restart: always
